# USDH token config for self-hosted clearnode on Sepolia
# 1 billion USDH minted to 0x07f412ad9D23Fcd328c209FaC7844F9F7A0ccED4

assets:
  - name: "House USD"
    symbol: "usdh"
    tokens:
      - blockchain_id: 11155111
        address: "0x25FfCCE632a03898c2ecB0EF9bb6a86177a363Ed"
        decimals: 6
