# Sepolia blockchain config for self-hosted clearnode
# Contracts deployed by 0x07f412ad9D23Fcd328c209FaC7844F9F7A0ccED4

default_contract_addresses:

blockchains:
- name: ethereum_sepolia
  id: 11155111
  contract_addresses:
    custody: "0xEC94b4039237ac9490377FDB8A65e884eD6154A0"
    adjudicator: "0x27f6C661929E4BF44455eEE2A7fc3C61E5AE768d"
    balance_checker: "0xd34eB26B1Df1F65Ce3318eB3872fa33BB86aa0e3"
